[versions]
agp = "8.13.2"  # Gradle 9와 호환되는 AGP 버전 (8.7+ 필요, 8.13.2는 Gradle 9 지원)
android_lint_reporter = "2.1.0"
reownBom = "1.5.2"  # Reown SDK (WalletConnect의 새로운 이름)
appUpdate = "2.1.0"
bcprovJdk15onVersion = "1.70"
bcprovJdk18onVersion = "1.77"
biometric = "1.1.0"
compiler = "5.0.5"
core = "3.5.4"
coreSplashscreen = "1.2.0"
detektGradlePlugin = "1.23.5"
firebaseAnalytics = "23.0.0"
firebaseCrashlytics = "20.0.3"
firebaseCrashlyticsGradle = "2.9.9"
firebaseMessaging = "25.0.1"
flexboxLayout = "2.0.1"
glide = "5.0.5"
googleServices = "4.4.2"
# Gradle wrapper 버전은 gradle-wrapper.properties에서 관리
# gradleWrapper = "9.2.1"  # 주석 처리 (wrapper.properties에서 직접 관리)
gridlayout = "1.1.0"
gson = "2.13.2"
guava = "33.5.0-android"
hiltAndroidGradlePlugin = "2.57.2"
jacocoAndroid = "0.1.5"
jsonSimple = "4.0.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
keyboardvisibilityevent = "3.0.0-RC3"
kotlinGradlePlugin = "2.0.0"
kotson = "2.5.0"
mailchimpSdkAndroid = "1.0.0"
material = "1.13.0"
constraintlayout = "2.2.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.8"
localbroadcastmanager = "1.1.0"
mixpanelAndroid = "8.2.4"
navigationFragment = "2.8.4"
navigationUi = "2.8.4"
okhttp = "5.3.2"
preferenceKtx = "1.2.1"
realmGradlePlugin = "10.19.0"  # 현재 최신 안정 버전 (10.20.0은 아직 릴리즈되지 않음)
recyclerview = "1.4.0"
review = "2.0.2"
rxjava = "2.2.21"
rxandroid = "2.1.1"
slf4jApi = "2.0.17"
springBootGradlePlugin = "2.2.2.RELEASE"
swiperefreshlayout = "1.2.0"
timber = "5.0.1"
# TRON Trident SDK - Maven Central에서 가져옴
# 참고: https://tronprotocol.github.io/trident/
# 버전 0.9.2 이상은 Maven Central에 등록됨
# 최신 버전 확인: https://search.maven.org/artifact/io.github.tronprotocol/trident
tronTrident = "0.9.2" # Maven Central에서 확인한 최신 버전으로 업데이트 가능
vectordrawable = "1.2.0"
walletCore = "4.5.0" # 최신 버전 (2025년 12월 24일 릴리스) - TRON 지원 확인 필요
webkit = "1.15.0"
workRuntimeKtx = "2.11.0"
zxingAndroidEmbedded = "4.3.0"
annotations = "26.0.2-1"

[libraries]
reown-bom = { module = "com.reown:android-bom", version.ref = "reownBom" }
android_lint_reporter = { module = "gradle.plugin.com.worker8.android_lint_reporter:android_lint_reporter", version.ref = "android_lint_reporter" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
bouncycastle-bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bcprovJdk15onVersion" }
bouncycastle-bcprov-jdk18on = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bcprovJdk18onVersion" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
core = { module = "com.google.zxing:core", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detektGradlePlugin" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", version.ref = "firebaseAnalytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
flexbox-layout = { module = "com.github.google:flexbox-layout", version.ref = "flexboxLayout" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }  # AGP 버전은 agp 참조 사용
gridlayout = { module = "androidx.gridlayout:gridlayout", version.ref = "gridlayout" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroidGradlePlugin" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hiltAndroidGradlePlugin" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroidGradlePlugin" }
jacoco-android = { module = "com.dicedmelon.gradle:jacoco-android", version.ref = "jacocoAndroid" }
json-simple = { module = "com.github.cliftonlabs:json-simple", version.ref = "jsonSimple" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
keyboardvisibilityevent = { module = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent", version.ref = "keyboardvisibilityevent" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotson = { module = "com.github.salomonbrys.kotson:kotson", version.ref = "kotson" }
mailchimp-sdk-android = { module = "com.github.mailchimp:mailchimp-sdk-android", version.ref = "mailchimpSdkAndroid" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
localbroadcastmanager = { module = "androidx.localbroadcastmanager:localbroadcastmanager", version.ref = "localbroadcastmanager" }
mixpanel-android = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanelAndroid" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
realm-gradle-plugin = { module = "io.realm:realm-gradle-plugin", version.ref = "realmGradlePlugin" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
review = { module = "com.google.android.play:review", version.ref = "review" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
spring-boot-gradle-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "springBootGradlePlugin" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
# TRON Trident SDK - Maven Central에서 가져옴
# 참고: https://tronprotocol.github.io/trident/
# 공식 문서: https://developers.tron.network/
tron-trident = { module = "io.github.tronprotocol:trident", version.ref = "tronTrident" }
vectordrawable = { module = "androidx.vectordrawable:vectordrawable", version.ref = "vectordrawable" }
wallet-core = { module = "com.trustwallet:wallet-core", version.ref = "walletCore" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

